name: 'Publish to the Vaadin Directory'

env:
  ADDON: delayedbutton  

on:
  release:
    types: [published]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build with Maven for Directory
      run: mvn -B install -Pdirectory --file pom.xml
    - name: Rename the war and remove the version
      run: mv sortable-layout/target/${ADDON}*.zip ${ADDON}.zip
    - name: Upload to Vaadin Directory
      uses: wei/curl@v1
      with:
        args: -X POST "https://vaadin.com/vaadincom/directory-service/upload/${ADDON}" -F "authKey=${{ secrets.DIRECTORY_AUTH_KEY }}" -F "publish=false" -F "releaseNotes=test" -H "accept:\ */*" -H "Content-Type:\ multipart/form-data" -F "file=@sortable-layout.zip;type=application/zip"
    - name: The Publish has failed
      if: ${{ job.status == 'failure' }}
      run: echo Job failed with status ${job.status}
